# Base de Datos de Autoridades Aduaneras Mundiales
# TaricAI - Sistema Internacional de Clasificación Arancelaria
# Última actualización: Diciembre 2025

WORLDWIDE_CUSTOMS_DATABASE = {
    # ========================
    # EUROPA - UNIÓN EUROPEA
    # ========================
    "ES": {
        "name": "España",
        "name_en": "Spain",
        "region": "Europa",
        "subregion": "Europa Occidental",
        "customs_authority": "Agencia Estatal de Administración Tributaria (AEAT)",
        "customs_website": "https://sede.agenciatributaria.gob.es/Sede/aduanas.html",
        "tariff_database": "https://sede.agenciatributaria.gob.es/Sede/aduanas/arancel-integrado-de-aplicacion-taric.html",
        "phytosanitary_authority": "Ministerio de Agricultura, Pesca y Alimentación (MAPA)",
        "phytosanitary_website": "https://www.mapa.gob.es/es/agricultura/temas/sanidad-vegetal/",
        "trade_ministry": "Ministerio de Industria, Comercio y Turismo",
        "trade_website": "https://comercio.gob.es/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 21,
        "reduced_vat": [10, 4],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Mexico", "EU-Japan EPA", "EU-Canada CETA", "EU-UK TCA", "EU-Chile", "EU-South Korea"],
        "import_requirements": [
            "Declaración Aduanera (DUA)",
            "Factura comercial",
            "Documentos de transporte (BL/AWB)",
            "Certificado de origen (según preferencias)",
            "Certificado fitosanitario (productos vegetales)",
            "Certificado sanitario (productos animales)"
        ],
        "special_notes": "Sistema TARIC integrado de la UE. Código EORI obligatorio para operadores."
    },
    "DE": {
        "name": "Alemania",
        "name_en": "Germany",
        "region": "Europa",
        "subregion": "Europa Occidental",
        "customs_authority": "Bundeszollverwaltung (Zoll)",
        "customs_website": "https://www.zoll.de/",
        "tariff_database": "https://www.zolltarifnummern.de/",
        "phytosanitary_authority": "Bundesamt für Verbraucherschutz und Lebensmittelsicherheit (BVL)",
        "phytosanitary_website": "https://www.bvl.bund.de/",
        "trade_ministry": "Bundesministerium für Wirtschaft und Klimaschutz",
        "trade_website": "https://www.bmwk.de/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 19,
        "reduced_vat": [7],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": [
            "ATLAS elektronische Zollanmeldung",
            "Handelsrechnung",
            "Frachtpapiere",
            "Ursprungszeugnis"
        ],
        "special_notes": "Portal ZOLL para declaraciones electrónicas. EORI obligatorio."
    },
    "FR": {
        "name": "Francia",
        "name_en": "France",
        "region": "Europa",
        "subregion": "Europa Occidental",
        "customs_authority": "Direction Générale des Douanes et Droits Indirects (DGDDI)",
        "customs_website": "https://www.douane.gouv.fr/",
        "tariff_database": "https://www.douane.gouv.fr/service-en-ligne/rita",
        "phytosanitary_authority": "Direction Générale de l'Alimentation (DGAL)",
        "phytosanitary_website": "https://agriculture.gouv.fr/direction-generale-de-lalimentation-dgal",
        "trade_ministry": "Direction Générale du Trésor",
        "trade_website": "https://www.tresor.economie.gouv.fr/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 20,
        "reduced_vat": [10, 5.5, 2.1],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": [
            "Déclaration en douane (DAU)",
            "Facture commerciale",
            "Document de transport",
            "Certificat d'origine"
        ],
        "special_notes": "Sistema DELTA para declaraciones. EORI obligatorio."
    },
    "IT": {
        "name": "Italia",
        "name_en": "Italy",
        "region": "Europa",
        "subregion": "Europa Meridional",
        "customs_authority": "Agenzia delle Dogane e dei Monopoli (ADM)",
        "customs_website": "https://www.adm.gov.it/",
        "tariff_database": "https://www.adm.gov.it/portale/taric",
        "phytosanitary_authority": "Ministero della Salute - Direzione Generale per l'Igiene e la Sicurezza degli Alimenti",
        "phytosanitary_website": "https://www.salute.gov.it/",
        "trade_ministry": "Ministero degli Affari Esteri e della Cooperazione Internazionale",
        "trade_website": "https://www.esteri.it/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 22,
        "reduced_vat": [10, 5, 4],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": [
            "Dichiarazione doganale",
            "Fattura commerciale",
            "Documenti di trasporto",
            "Certificato di origine"
        ],
        "special_notes": "Sistema AIDA para declaraciones electrónicas."
    },
    "PT": {
        "name": "Portugal",
        "name_en": "Portugal",
        "region": "Europa",
        "subregion": "Europa Meridional",
        "customs_authority": "Autoridade Tributária e Aduaneira (AT)",
        "customs_website": "https://www.portaldasfinancas.gov.pt/",
        "tariff_database": "https://pauta.portaldasfinancas.gov.pt/",
        "phytosanitary_authority": "Direção-Geral de Alimentação e Veterinária (DGAV)",
        "phytosanitary_website": "https://www.dgav.pt/",
        "trade_ministry": "AICEP Portugal Global",
        "trade_website": "https://www.portugalglobal.pt/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 23,
        "reduced_vat": [13, 6],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Declaração Aduaneira Única (DAU)", "Fatura comercial", "Documentos de transporte"],
        "special_notes": "Portal das Finanças para declaraciones."
    },
    "NL": {
        "name": "Países Bajos",
        "name_en": "Netherlands",
        "region": "Europa",
        "subregion": "Europa Occidental",
        "customs_authority": "Douane Nederland",
        "customs_website": "https://www.belastingdienst.nl/wps/wcm/connect/nl/douane/",
        "tariff_database": "https://tarief.douane.nl/",
        "phytosanitary_authority": "Nederlandse Voedsel- en Warenautoriteit (NVWA)",
        "phytosanitary_website": "https://www.nvwa.nl/",
        "trade_ministry": "Rijksdienst voor Ondernemend Nederland (RVO)",
        "trade_website": "https://www.rvo.nl/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 21,
        "reduced_vat": [9],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Douaneaangifte", "Handelsfactuur", "Vervoersdocumenten"],
        "special_notes": "Puerto de Rotterdam - mayor puerto de Europa. Sistema AGS."
    },
    "BE": {
        "name": "Bélgica",
        "name_en": "Belgium",
        "region": "Europa",
        "subregion": "Europa Occidental",
        "customs_authority": "Administration Générale des Douanes et Accises (AGDA)",
        "customs_website": "https://finance.belgium.be/fr/douanes_et_accises",
        "tariff_database": "https://www.tarweb.be/",
        "phytosanitary_authority": "Agence Fédérale pour la Sécurité de la Chaîne Alimentaire (AFSCA)",
        "phytosanitary_website": "https://www.afsca.be/",
        "trade_ministry": "Service Public Fédéral Économie",
        "trade_website": "https://economie.fgov.be/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 21,
        "reduced_vat": [12, 6],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Déclaration en douane", "Facture commerciale", "Documents de transport"],
        "special_notes": "Puerto de Amberes - segundo puerto más grande de Europa."
    },
    "PL": {
        "name": "Polonia",
        "name_en": "Poland",
        "region": "Europa",
        "subregion": "Europa Central",
        "customs_authority": "Krajowa Administracja Skarbowa (KAS)",
        "customs_website": "https://www.gov.pl/web/kas",
        "tariff_database": "https://isztar4.mf.gov.pl/taryfa_celna/",
        "phytosanitary_authority": "Główny Inspektorat Ochrony Roślin i Nasiennictwa",
        "phytosanitary_website": "https://piorin.gov.pl/",
        "trade_ministry": "Ministerstwo Rozwoju i Technologii",
        "trade_website": "https://www.gov.pl/web/rozwoj-technologia",
        "eu_member": True,
        "currency": "PLN",
        "vat_rate": 23,
        "reduced_vat": [8, 5, 0],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Zgłoszenie celne", "Faktura handlowa", "Dokumenty przewozowe"],
        "special_notes": "Sistema PUESC para declaraciones electrónicas."
    },
    "SE": {
        "name": "Suecia",
        "name_en": "Sweden",
        "region": "Europa",
        "subregion": "Europa del Norte",
        "customs_authority": "Tullverket",
        "customs_website": "https://www.tullverket.se/",
        "tariff_database": "https://tulltaxan.tullverket.se/",
        "phytosanitary_authority": "Jordbruksverket",
        "phytosanitary_website": "https://www.jordbruksverket.se/",
        "trade_ministry": "Business Sweden",
        "trade_website": "https://www.business-sweden.com/",
        "eu_member": True,
        "currency": "SEK",
        "vat_rate": 25,
        "reduced_vat": [12, 6],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Tulldeklaration", "Handelsfaktura", "Fraktdokument"],
        "special_notes": "Sistema TDS para declaraciones electrónicas."
    },
    "AT": {
        "name": "Austria",
        "name_en": "Austria",
        "region": "Europa",
        "subregion": "Europa Central",
        "customs_authority": "Bundesministerium für Finanzen - Zollamt",
        "customs_website": "https://www.bmf.gv.at/zoll.html",
        "tariff_database": "https://zolltarifauskunft.bmf.gv.at/",
        "phytosanitary_authority": "AGES - Österreichische Agentur für Gesundheit und Ernährungssicherheit",
        "phytosanitary_website": "https://www.ages.at/",
        "trade_ministry": "Wirtschaftskammer Österreich",
        "trade_website": "https://www.wko.at/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 20,
        "reduced_vat": [13, 10],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Zollanmeldung", "Handelsrechnung", "Frachtpapiere"],
        "special_notes": "Sistema e-zoll para declaraciones electrónicas."
    },
    "GR": {
        "name": "Grecia",
        "name_en": "Greece",
        "region": "Europa",
        "subregion": "Europa Meridional",
        "customs_authority": "Ανεξάρτητη Αρχή Δημοσίων Εσόδων (AADE)",
        "customs_website": "https://www.aade.gr/",
        "tariff_database": "https://portal.aade.gr/",
        "phytosanitary_authority": "Υπουργείο Αγροτικής Ανάπτυξης και Τροφίμων",
        "phytosanitary_website": "https://www.minagric.gr/",
        "trade_ministry": "Enterprise Greece",
        "trade_website": "https://www.enterprisegreece.gov.gr/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 24,
        "reduced_vat": [13, 6],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Τελωνειακή διασάφηση", "Εμπορικό τιμολόγιο", "Έγγραφα μεταφοράς"],
        "special_notes": "Puerto de El Pireo - importante hub del Mediterráneo."
    },
    "CZ": {
        "name": "República Checa",
        "name_en": "Czech Republic",
        "region": "Europa",
        "subregion": "Europa Central",
        "customs_authority": "Celní správa České republiky",
        "customs_website": "https://www.celnisprava.cz/",
        "tariff_database": "https://www.celnisprava.cz/cz/aplikace/Stranky/taric-cz.aspx",
        "phytosanitary_authority": "Státní rostlinolékařská správa",
        "phytosanitary_website": "http://eagri.cz/public/web/srs/",
        "trade_ministry": "CzechTrade",
        "trade_website": "https://www.czechtrade.cz/",
        "eu_member": True,
        "currency": "CZK",
        "vat_rate": 21,
        "reduced_vat": [15, 10],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Celní prohlášení", "Obchodní faktura", "Přepravní dokumenty"],
        "special_notes": "Sistema e-Customs para declaraciones electrónicas."
    },
    "RO": {
        "name": "Rumania",
        "name_en": "Romania",
        "region": "Europa",
        "subregion": "Europa del Este",
        "customs_authority": "Autoritatea Vamală Română",
        "customs_website": "https://www.customs.ro/",
        "tariff_database": "https://www.customs.ro/agenti-economici/tariful-vamal",
        "phytosanitary_authority": "Autoritatea Națională Fitosanitară",
        "phytosanitary_website": "http://www.anfdf.ro/",
        "trade_ministry": "Ministerul Economiei",
        "trade_website": "http://www.economie.gov.ro/",
        "eu_member": True,
        "currency": "RON",
        "vat_rate": 19,
        "reduced_vat": [9, 5],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Declarație vamală", "Factură comercială", "Documente de transport"],
        "special_notes": "Puerto de Constanza en el Mar Negro."
    },
    "HU": {
        "name": "Hungría",
        "name_en": "Hungary",
        "region": "Europa",
        "subregion": "Europa Central",
        "customs_authority": "Nemzeti Adó- és Vámhivatal (NAV)",
        "customs_website": "https://nav.gov.hu/",
        "tariff_database": "https://nav.gov.hu/vaminfo",
        "phytosanitary_authority": "Nemzeti Élelmiszerlánc-biztonsági Hivatal (NÉBIH)",
        "phytosanitary_website": "https://portal.nebih.gov.hu/",
        "trade_ministry": "Hungarian Investment Promotion Agency (HIPA)",
        "trade_website": "https://hipa.hu/",
        "eu_member": True,
        "currency": "HUF",
        "vat_rate": 27,
        "reduced_vat": [18, 5],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Vámáru-nyilatkozat", "Kereskedelmi számla", "Fuvarokmányok"],
        "special_notes": "IVA más alto de la UE (27%)."
    },
    "IE": {
        "name": "Irlanda",
        "name_en": "Ireland",
        "region": "Europa",
        "subregion": "Europa Occidental",
        "customs_authority": "Revenue Commissioners - Customs Division",
        "customs_website": "https://www.revenue.ie/en/customs/index.aspx",
        "tariff_database": "https://www.revenue.ie/en/customs/businesses/electronic-systems/taric/index.aspx",
        "phytosanitary_authority": "Department of Agriculture, Food and the Marine",
        "phytosanitary_website": "https://www.gov.ie/en/organisation/department-of-agriculture-food-and-the-marine/",
        "trade_ministry": "Enterprise Ireland",
        "trade_website": "https://www.enterprise-ireland.com/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 23,
        "reduced_vat": [13.5, 9, 4.8],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Customs Declaration", "Commercial Invoice", "Transport Documents"],
        "special_notes": "Hub tecnológico europeo. Sistema AIS para declaraciones."
    },
    "DK": {
        "name": "Dinamarca",
        "name_en": "Denmark",
        "region": "Europa",
        "subregion": "Europa del Norte",
        "customs_authority": "Toldstyrelsen",
        "customs_website": "https://www.toldst.dk/",
        "tariff_database": "https://skat.dk/data.aspx?oid=2234504",
        "phytosanitary_authority": "Fødevarestyrelsen",
        "phytosanitary_website": "https://www.foedevarestyrelsen.dk/",
        "trade_ministry": "The Trade Council of Denmark",
        "trade_website": "https://thetradecouncil.dk/",
        "eu_member": True,
        "currency": "DKK",
        "vat_rate": 25,
        "reduced_vat": [],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Toldangivelse", "Handelsfaktura", "Transportdokumenter"],
        "special_notes": "Sin IVA reducido - tasa única del 25%."
    },
    "FI": {
        "name": "Finlandia",
        "name_en": "Finland",
        "region": "Europa",
        "subregion": "Europa del Norte",
        "customs_authority": "Tulli",
        "customs_website": "https://tulli.fi/",
        "tariff_database": "https://tulli.fi/en/businesses/tariff-classification",
        "phytosanitary_authority": "Ruokavirasto (Finnish Food Authority)",
        "phytosanitary_website": "https://www.ruokavirasto.fi/",
        "trade_ministry": "Business Finland",
        "trade_website": "https://www.businessfinland.fi/",
        "eu_member": True,
        "currency": "EUR",
        "vat_rate": 24,
        "reduced_vat": [14, 10],
        "hs_system": "TARIC (EU Combined Nomenclature)",
        "trade_agreements": ["EU Single Market", "EU-Japan EPA", "EU-Canada CETA"],
        "import_requirements": ["Tulli-ilmoitus", "Kauppalasku", "Kuljetusasiakirjat"],
        "special_notes": "Frontera directa con Rusia."
    },
    
    # ========================
    # EUROPA - NO UE
    # ========================
    "GB": {
        "name": "Reino Unido",
        "name_en": "United Kingdom",
        "region": "Europa",
        "subregion": "Europa Occidental",
        "customs_authority": "HM Revenue & Customs (HMRC)",
        "customs_website": "https://www.gov.uk/government/organisations/hm-revenue-customs",
        "tariff_database": "https://www.trade-tariff.service.gov.uk/",
        "phytosanitary_authority": "Animal and Plant Health Agency (APHA)",
        "phytosanitary_website": "https://www.gov.uk/government/organisations/animal-and-plant-health-agency",
        "trade_ministry": "Department for Business and Trade",
        "trade_website": "https://www.great.gov.uk/",
        "eu_member": False,
        "currency": "GBP",
        "vat_rate": 20,
        "reduced_vat": [5, 0],
        "hs_system": "UK Global Tariff",
        "trade_agreements": ["UK-EU TCA", "UK-Japan CEPA", "UK-Australia FTA", "UK-New Zealand FTA", "CPTPP"],
        "import_requirements": [
            "Customs Declaration (CDS)",
            "Commercial Invoice",
            "Import Licence (if required)",
            "Certificate of Origin",
            "Phytosanitary Certificate (plant products)"
        ],
        "special_notes": "Post-Brexit: requiere declaraciones aduaneras para comercio con UE. Sistema CDS obligatorio."
    },
    "CH": {
        "name": "Suiza",
        "name_en": "Switzerland",
        "region": "Europa",
        "subregion": "Europa Occidental",
        "customs_authority": "Bundesamt für Zoll und Grenzsicherheit (BAZG)",
        "customs_website": "https://www.bazg.admin.ch/",
        "tariff_database": "https://www.tares.ch/",
        "phytosanitary_authority": "Bundesamt für Landwirtschaft (BLW)",
        "phytosanitary_website": "https://www.blw.admin.ch/",
        "trade_ministry": "State Secretariat for Economic Affairs (SECO)",
        "trade_website": "https://www.seco.admin.ch/",
        "eu_member": False,
        "currency": "CHF",
        "vat_rate": 8.1,
        "reduced_vat": [2.6],
        "hs_system": "Swiss Tariff (aligned with HS)",
        "trade_agreements": ["EFTA", "Switzerland-EU Bilateral Agreements", "Switzerland-China FTA", "Switzerland-Japan FTA"],
        "import_requirements": ["Zollanmeldung", "Handelsrechnung", "Ursprungsnachweis", "Veterinärzertifikat (Tierprodukte)"],
        "special_notes": "No es miembro de UE ni EEE. Acuerdos bilaterales con UE. IVA bajo (8.1%)."
    },
    "NO": {
        "name": "Noruega",
        "name_en": "Norway",
        "region": "Europa",
        "subregion": "Europa del Norte",
        "customs_authority": "Tolletaten",
        "customs_website": "https://www.toll.no/",
        "tariff_database": "https://tolltariffen.toll.no/",
        "phytosanitary_authority": "Mattilsynet",
        "phytosanitary_website": "https://www.mattilsynet.no/",
        "trade_ministry": "Innovation Norway",
        "trade_website": "https://www.innovasjonnorge.no/",
        "eu_member": False,
        "currency": "NOK",
        "vat_rate": 25,
        "reduced_vat": [15, 12],
        "hs_system": "Norwegian Customs Tariff (aligned with HS)",
        "trade_agreements": ["EEA Agreement", "EFTA", "Norway-EU Agreement"],
        "import_requirements": ["Tolldeklarasjon", "Handelsfaktura", "Transportdokumenter", "Opprinnelsesbevis"],
        "special_notes": "Miembro del EEE pero no de la UE. Alto nivel de protección agrícola."
    },
    "RU": {
        "name": "Rusia",
        "name_en": "Russia",
        "region": "Europa/Asia",
        "subregion": "Europa del Este",
        "customs_authority": "Federal Customs Service (FCS Russia)",
        "customs_website": "https://customs.gov.ru/",
        "tariff_database": "http://www.tks.ru/",
        "phytosanitary_authority": "Rosselkhoznadzor",
        "phytosanitary_website": "https://fsvps.gov.ru/",
        "trade_ministry": "Ministry of Economic Development",
        "trade_website": "https://www.economy.gov.ru/",
        "eu_member": False,
        "currency": "RUB",
        "vat_rate": 20,
        "reduced_vat": [10, 0],
        "hs_system": "Eurasian Economic Union Common Customs Tariff",
        "trade_agreements": ["EAEU (Eurasian Economic Union)", "CIS Free Trade Agreement", "Russia-Vietnam FTA"],
        "import_requirements": [
            "Customs Declaration",
            "Commercial Invoice",
            "Transport Documents",
            "Certificate of Conformity (GOST)",
            "Phytosanitary Certificate"
        ],
        "special_notes": "⚠️ Sanciones internacionales vigentes (2022-presente). Miembro de la EAEU. Verificar restricciones antes de exportar."
    },
    "UA": {
        "name": "Ucrania",
        "name_en": "Ukraine",
        "region": "Europa",
        "subregion": "Europa del Este",
        "customs_authority": "State Customs Service of Ukraine",
        "customs_website": "https://customs.gov.ua/",
        "tariff_database": "https://cabinet.customs.gov.ua/",
        "phytosanitary_authority": "State Service of Ukraine for Food Safety and Consumer Protection",
        "phytosanitary_website": "https://dpss.gov.ua/",
        "trade_ministry": "Ministry of Economy of Ukraine",
        "trade_website": "https://www.me.gov.ua/",
        "eu_member": False,
        "currency": "UAH",
        "vat_rate": 20,
        "reduced_vat": [7, 0],
        "hs_system": "Ukrainian Customs Tariff (aligned with HS)",
        "trade_agreements": ["EU-Ukraine DCFTA", "Ukraine-UK FTA", "Ukraine-Canada FTA"],
        "import_requirements": ["Customs Declaration", "Commercial Invoice", "Certificate of Origin"],
        "special_notes": "⚠️ Conflicto activo. Verificar rutas y restricciones logísticas. DCFTA con UE."
    },
    "TR": {
        "name": "Turquía",
        "name_en": "Turkey",
        "region": "Europa/Asia",
        "subregion": "Asia Occidental",
        "customs_authority": "T.C. Ticaret Bakanlığı (Ministry of Trade)",
        "customs_website": "https://ticaret.gov.tr/gumruk-islemleri",
        "tariff_database": "https://gumrukrehberi.gov.tr/",
        "phytosanitary_authority": "Ministry of Agriculture and Forestry",
        "phytosanitary_website": "https://www.tarimorman.gov.tr/",
        "trade_ministry": "Ministry of Trade",
        "trade_website": "https://www.trade.gov.tr/",
        "eu_member": False,
        "currency": "TRY",
        "vat_rate": 20,
        "reduced_vat": [10, 1],
        "hs_system": "Turkish Customs Tariff (aligned with EU CN for most goods)",
        "trade_agreements": ["EU-Turkey Customs Union", "Turkey-UK FTA", "Turkey-South Korea FTA", "EFTA-Turkey"],
        "import_requirements": [
            "Gümrük Beyannamesi",
            "Ticari Fatura",
            "Taşıma Belgeleri",
            "Menşe Şahadetnamesi",
            "TAREKS Reference (textiles)"
        ],
        "special_notes": "Unión Aduanera con UE para productos industriales. Sistema TAREKS para control de productos."
    },
    
    # ========================
    # AMÉRICA DEL NORTE
    # ========================
    "US": {
        "name": "Estados Unidos",
        "name_en": "United States",
        "region": "América",
        "subregion": "América del Norte",
        "customs_authority": "U.S. Customs and Border Protection (CBP)",
        "customs_website": "https://www.cbp.gov/",
        "tariff_database": "https://hts.usitc.gov/",
        "phytosanitary_authority": "USDA APHIS (Animal and Plant Health Inspection Service)",
        "phytosanitary_website": "https://www.aphis.usda.gov/",
        "food_safety_authority": "FDA (Food and Drug Administration)",
        "food_safety_website": "https://www.fda.gov/",
        "trade_ministry": "U.S. International Trade Administration",
        "trade_website": "https://www.trade.gov/",
        "eu_member": False,
        "currency": "USD",
        "vat_rate": 0,
        "sales_tax_note": "Sales tax varía por estado (0-10.25%)",
        "hs_system": "Harmonized Tariff Schedule of the United States (HTSUS)",
        "trade_agreements": ["USMCA", "US-Korea FTA", "US-Australia FTA", "US-Chile FTA", "US-Singapore FTA", "US-Israel FTA"],
        "import_requirements": [
            "CBP Form 3461 (Entry)",
            "CBP Form 7501 (Entry Summary)",
            "Commercial Invoice",
            "Bill of Lading/Airway Bill",
            "Packing List",
            "Certificate of Origin (FTA claims)",
            "FDA Prior Notice (food products)",
            "Lacey Act Declaration (wood/plants)"
        ],
        "special_notes": "Sin IVA federal. Aranceles variables según administración. Importador de registro obligatorio."
    },
    "CA": {
        "name": "Canadá",
        "name_en": "Canada",
        "region": "América",
        "subregion": "América del Norte",
        "customs_authority": "Canada Border Services Agency (CBSA)",
        "customs_website": "https://www.cbsa-asfc.gc.ca/",
        "tariff_database": "https://www.cbsa-asfc.gc.ca/trade-commerce/tariff-tarif/",
        "phytosanitary_authority": "Canadian Food Inspection Agency (CFIA)",
        "phytosanitary_website": "https://www.inspection.gc.ca/",
        "trade_ministry": "Global Affairs Canada",
        "trade_website": "https://www.international.gc.ca/",
        "eu_member": False,
        "currency": "CAD",
        "vat_rate": 5,
        "provincial_tax_note": "GST 5% + PST provincial (0-10%)",
        "hs_system": "Canadian Customs Tariff",
        "trade_agreements": ["USMCA", "CETA (EU-Canada)", "CPTPP", "Canada-UK TCA", "Canada-Korea FTA"],
        "import_requirements": [
            "Canada Customs Coding Form (B3)",
            "Commercial Invoice",
            "Canada Customs Invoice (CCI) or Commercial Invoice",
            "Certificate of Origin",
            "Bill of Lading",
            "Packing List"
        ],
        "special_notes": "Sistema CARM para gestión de cuentas aduaneras. Bilingüe (inglés/francés)."
    },
    "MX": {
        "name": "México",
        "name_en": "Mexico",
        "region": "América",
        "subregion": "América del Norte",
        "customs_authority": "Agencia Nacional de Aduanas de México (ANAM) / SAT",
        "customs_website": "https://www.sat.gob.mx/",
        "tariff_database": "https://www.siicex.gob.mx/",
        "phytosanitary_authority": "SENASICA",
        "phytosanitary_website": "https://www.gob.mx/senasica",
        "trade_ministry": "Secretaría de Economía",
        "trade_website": "https://www.gob.mx/se",
        "eu_member": False,
        "currency": "MXN",
        "vat_rate": 16,
        "reduced_vat": [0],
        "hs_system": "Tarifa de la Ley de los Impuestos Generales de Importación y Exportación (TIGIE)",
        "trade_agreements": ["USMCA", "EU-Mexico FTA", "Pacific Alliance", "CPTPP", "Mexico-Japan EPA"],
        "import_requirements": [
            "Pedimento de Importación",
            "Factura Comercial",
            "Carta de Porte / Conocimiento de Embarque",
            "Certificado de Origen",
            "Permisos previos (según producto)",
            "NOM (Normas Oficiales Mexicanas)"
        ],
        "special_notes": "RFC obligatorio para importadores. Sistema VUCEM para trámites electrónicos."
    },
    
    # ========================
    # AMÉRICA LATINA
    # ========================
    "CO": {
        "name": "Colombia",
        "name_en": "Colombia",
        "region": "América",
        "subregion": "América del Sur",
        "customs_authority": "Dirección de Impuestos y Aduanas Nacionales (DIAN)",
        "customs_website": "https://www.dian.gov.co/",
        "tariff_database": "https://muisca.dian.gov.co/WebArancel/",
        "phytosanitary_authority": "Instituto Colombiano Agropecuario (ICA)",
        "phytosanitary_website": "https://www.ica.gov.co/",
        "sanitary_authority": "INVIMA",
        "sanitary_website": "https://www.invima.gov.co/",
        "trade_ministry": "Ministerio de Comercio, Industria y Turismo",
        "trade_website": "https://www.mincit.gov.co/",
        "eu_member": False,
        "currency": "COP",
        "vat_rate": 19,
        "reduced_vat": [5, 0],
        "hs_system": "Arancel de Aduanas de Colombia (basado en NANDINA)",
        "trade_agreements": ["Pacific Alliance", "CAN", "EU-Colombia FTA", "US-Colombia TPA", "Colombia-South Korea FTA"],
        "import_requirements": [
            "Declaración de Importación",
            "Factura Comercial",
            "Documento de Transporte",
            "Certificado de Origen",
            "Registro de Importación (VUCE)",
            "Certificado fitosanitario ICA (productos agrícolas)",
            "Registro sanitario INVIMA (alimentos/medicamentos)"
        ],
        "special_notes": "Sistema MUISCA para declaraciones. VUCE para ventanilla única."
    },
    "BR": {
        "name": "Brasil",
        "name_en": "Brazil",
        "region": "América",
        "subregion": "América del Sur",
        "customs_authority": "Receita Federal do Brasil",
        "customs_website": "https://www.gov.br/receitafederal/",
        "tariff_database": "http://www4.receita.fazenda.gov.br/simulador/",
        "phytosanitary_authority": "Ministério da Agricultura e Pecuária (MAPA)",
        "phytosanitary_website": "https://www.gov.br/agricultura/",
        "sanitary_authority": "ANVISA",
        "sanitary_website": "https://www.gov.br/anvisa/",
        "trade_ministry": "Ministério do Desenvolvimento, Indústria, Comércio e Serviços",
        "trade_website": "https://www.gov.br/mdic/",
        "eu_member": False,
        "currency": "BRL",
        "vat_rate": 0,
        "tax_note": "ICMS (17-25%) + IPI + PIS/COFINS = carga tributaria alta",
        "hs_system": "Nomenclatura Comum do Mercosul (NCM)",
        "trade_agreements": ["MERCOSUR", "MERCOSUR-EU (pending)", "MERCOSUR-Israel", "Brazil-Mexico ACE 53"],
        "import_requirements": [
            "Declaração de Importação (DI)",
            "Fatura Comercial",
            "Conhecimento de Embarque",
            "Certificado de Origem",
            "Licença de Importação (LI) - según producto",
            "Certificado fitossanitário MAPA"
        ],
        "special_notes": "Sistema Siscomex para comercio exterior. Alta carga tributaria en importaciones."
    },
    "AR": {
        "name": "Argentina",
        "name_en": "Argentina",
        "region": "América",
        "subregion": "América del Sur",
        "customs_authority": "Administración Federal de Ingresos Públicos (AFIP) - Dirección General de Aduanas",
        "customs_website": "https://www.afip.gob.ar/aduana/",
        "tariff_database": "https://www.afip.gob.ar/aduanaDefault.asp",
        "phytosanitary_authority": "SENASA",
        "phytosanitary_website": "https://www.argentina.gob.ar/senasa",
        "trade_ministry": "Secretaría de Comercio Interior y Exterior",
        "trade_website": "https://www.argentina.gob.ar/economia/comercio",
        "eu_member": False,
        "currency": "ARS",
        "vat_rate": 21,
        "reduced_vat": [10.5, 0],
        "hs_system": "Nomenclatura Común del Mercosur (NCM)",
        "trade_agreements": ["MERCOSUR", "MERCOSUR-EU (pending)", "Argentina-Chile ACE 35"],
        "import_requirements": [
            "Destinación de Importación",
            "Factura Comercial",
            "Documento de Transporte",
            "Certificado de Origen",
            "SIMI (Sistema Integral de Monitoreo de Importaciones)"
        ],
        "special_notes": "Controles cambiarios vigentes. Sistema MALVINA/SIMI para importaciones."
    },
    "CL": {
        "name": "Chile",
        "name_en": "Chile",
        "region": "América",
        "subregion": "América del Sur",
        "customs_authority": "Servicio Nacional de Aduanas (SNA)",
        "customs_website": "https://www.aduana.cl/",
        "tariff_database": "https://www.aduana.cl/arancel-aduanero/aduana/2019-02-20/155511.html",
        "phytosanitary_authority": "Servicio Agrícola y Ganadero (SAG)",
        "phytosanitary_website": "https://www.sag.gob.cl/",
        "trade_ministry": "Subsecretaría de Relaciones Económicas Internacionales (SUBREI)",
        "trade_website": "https://www.subrei.gob.cl/",
        "eu_member": False,
        "currency": "CLP",
        "vat_rate": 19,
        "reduced_vat": [],
        "hs_system": "Arancel Aduanero de Chile",
        "trade_agreements": ["Pacific Alliance", "EU-Chile AA", "US-Chile FTA", "CPTPP", "Chile-China FTA", "Chile-Japan EPA"],
        "import_requirements": [
            "Declaración de Ingreso (DIN)",
            "Factura Comercial",
            "Documento de Transporte",
            "Certificado de Origen",
            "Certificado fitosanitario SAG (productos agrícolas)"
        ],
        "special_notes": "País más abierto al comercio en Latam. Arancel general 6%. Más de 30 TLCs vigentes."
    },
    "PE": {
        "name": "Perú",
        "name_en": "Peru",
        "region": "América",
        "subregion": "América del Sur",
        "customs_authority": "Superintendencia Nacional de Aduanas y de Administración Tributaria (SUNAT)",
        "customs_website": "https://www.sunat.gob.pe/",
        "tariff_database": "http://www.aduanet.gob.pe/aduanas/informao/tra_ar.htm",
        "phytosanitary_authority": "SENASA Perú",
        "phytosanitary_website": "https://www.senasa.gob.pe/",
        "trade_ministry": "Ministerio de Comercio Exterior y Turismo (MINCETUR)",
        "trade_website": "https://www.gob.pe/mincetur",
        "eu_member": False,
        "currency": "PEN",
        "vat_rate": 18,
        "reduced_vat": [],
        "hs_system": "Arancel de Aduanas del Perú (basado en NANDINA)",
        "trade_agreements": ["Pacific Alliance", "CAN", "EU-Peru FTA", "US-Peru TPA", "Peru-China FTA", "CPTPP"],
        "import_requirements": [
            "Declaración Única de Aduanas (DUA)",
            "Factura Comercial",
            "Documento de Transporte",
            "Certificado de Origen",
            "Certificado fitosanitario SENASA"
        ],
        "special_notes": "Sistema VUCE para ventanilla única. Miembro de Pacific Alliance y CPTPP."
    },
    "EC": {
        "name": "Ecuador",
        "name_en": "Ecuador",
        "region": "América",
        "subregion": "América del Sur",
        "customs_authority": "Servicio Nacional de Aduana del Ecuador (SENAE)",
        "customs_website": "https://www.aduana.gob.ec/",
        "tariff_database": "https://www.aduana.gob.ec/arancel/",
        "phytosanitary_authority": "Agencia de Regulación y Control Fito y Zoosanitario (AGROCALIDAD)",
        "phytosanitary_website": "https://www.agrocalidad.gob.ec/",
        "trade_ministry": "Ministerio de Producción, Comercio Exterior, Inversiones y Pesca",
        "trade_website": "https://www.produccion.gob.ec/",
        "eu_member": False,
        "currency": "USD",
        "vat_rate": 15,
        "reduced_vat": [0],
        "hs_system": "Arancel Nacional de Importaciones (basado en NANDINA)",
        "trade_agreements": ["CAN", "EU-Ecuador Agreement", "Ecuador-China FTA (negotiating)"],
        "import_requirements": [
            "Declaración Aduanera de Importación (DAI)",
            "Factura Comercial",
            "Documento de Transporte",
            "Certificado de Origen",
            "Certificado fitosanitario AGROCALIDAD"
        ],
        "special_notes": "Economía dolarizada. Sistema ECUAPASS para comercio exterior."
    },
    "UY": {
        "name": "Uruguay",
        "name_en": "Uruguay",
        "region": "América",
        "subregion": "América del Sur",
        "customs_authority": "Dirección Nacional de Aduanas (DNA)",
        "customs_website": "https://www.aduanas.gub.uy/",
        "tariff_database": "https://www.aduanas.gub.uy/innovaportal/v/234/1/innova.front/nomenclatura.html",
        "phytosanitary_authority": "Ministerio de Ganadería, Agricultura y Pesca (MGAP)",
        "phytosanitary_website": "https://www.gub.uy/ministerio-ganaderia-agricultura-pesca/",
        "trade_ministry": "Uruguay XXI",
        "trade_website": "https://www.uruguayxxi.gub.uy/",
        "eu_member": False,
        "currency": "UYU",
        "vat_rate": 22,
        "reduced_vat": [10, 0],
        "hs_system": "Nomenclatura Común del Mercosur (NCM)",
        "trade_agreements": ["MERCOSUR", "MERCOSUR-EU (pending)"],
        "import_requirements": ["Declaración de Importación", "Factura Comercial", "Documento de Transporte", "Certificado de Origen"],
        "special_notes": "Sistema LUCIA para declaraciones aduaneras."
    },
    "PY": {
        "name": "Paraguay",
        "name_en": "Paraguay",
        "region": "América",
        "subregion": "América del Sur",
        "customs_authority": "Dirección Nacional de Aduanas (DNA)",
        "customs_website": "https://www.aduana.gov.py/",
        "tariff_database": "https://www.aduana.gov.py/arancel.html",
        "phytosanitary_authority": "SENAVE",
        "phytosanitary_website": "https://www.senave.gov.py/",
        "trade_ministry": "Red de Inversiones y Exportaciones (REDIEX)",
        "trade_website": "https://www.rediex.gov.py/",
        "eu_member": False,
        "currency": "PYG",
        "vat_rate": 10,
        "reduced_vat": [5],
        "hs_system": "Nomenclatura Común del Mercosur (NCM)",
        "trade_agreements": ["MERCOSUR", "MERCOSUR-EU (pending)"],
        "import_requirements": ["Declaración Aduanera", "Factura Comercial", "Documento de Transporte", "Certificado de Origen"],
        "special_notes": "País sin litoral. Sistema SOFIA para aduanas."
    },
    "BO": {
        "name": "Bolivia",
        "name_en": "Bolivia",
        "region": "América",
        "subregion": "América del Sur",
        "customs_authority": "Aduana Nacional de Bolivia",
        "customs_website": "https://www.aduana.gob.bo/",
        "tariff_database": "https://www.aduana.gob.bo/arancel/",
        "phytosanitary_authority": "SENASAG",
        "phytosanitary_website": "https://www.senasag.gob.bo/",
        "trade_ministry": "Ministerio de Desarrollo Productivo y Economía Plural",
        "trade_website": "https://www.produccion.gob.bo/",
        "eu_member": False,
        "currency": "BOB",
        "vat_rate": 13,
        "reduced_vat": [],
        "hs_system": "Arancel Aduanero de Importaciones (basado en NANDINA)",
        "trade_agreements": ["CAN", "MERCOSUR (Associate)", "Bolivia-Mexico ACE 66"],
        "import_requirements": ["Declaración Única de Importación (DUI)", "Factura Comercial", "Documento de Transporte", "Certificado de Origen"],
        "special_notes": "País sin litoral. Miembro asociado del MERCOSUR."
    },
    "VE": {
        "name": "Venezuela",
        "name_en": "Venezuela",
        "region": "América",
        "subregion": "América del Sur",
        "customs_authority": "Servicio Nacional Integrado de Administración Aduanera y Tributaria (SENIAT)",
        "customs_website": "http://www.seniat.gob.ve/",
        "tariff_database": "http://www.seniat.gob.ve/",
        "phytosanitary_authority": "INSAI",
        "phytosanitary_website": "http://www.insai.gob.ve/",
        "trade_ministry": "Ministerio del Poder Popular para Comercio Exterior",
        "trade_website": "http://www.mincomercio.gob.ve/",
        "eu_member": False,
        "currency": "VES",
        "vat_rate": 16,
        "reduced_vat": [8],
        "hs_system": "Arancel de Aduanas de Venezuela",
        "trade_agreements": ["MERCOSUR (suspended)", "ALBA", "Petrocaribe"],
        "import_requirements": ["Declaración Única de Aduanas", "Factura Comercial", "Documento de Transporte"],
        "special_notes": "⚠️ Sanciones internacionales. Controles de cambio estrictos. Verificar restricciones."
    },
    
    # ========================
    # AMÉRICA CENTRAL Y CARIBE
    # ========================
    "PA": {
        "name": "Panamá",
        "name_en": "Panama",
        "region": "América",
        "subregion": "América Central",
        "customs_authority": "Autoridad Nacional de Aduanas (ANA)",
        "customs_website": "https://www.ana.gob.pa/",
        "tariff_database": "https://www.ana.gob.pa/arancel/",
        "phytosanitary_authority": "Autoridad Panameña de Seguridad de Alimentos (AUPSA)",
        "phytosanitary_website": "https://www.aupsa.gob.pa/",
        "trade_ministry": "Ministerio de Comercio e Industrias",
        "trade_website": "https://www.mici.gob.pa/",
        "eu_member": False,
        "currency": "USD/PAB",
        "vat_rate": 7,
        "reduced_vat": [],
        "hs_system": "Arancel Nacional de Importación",
        "trade_agreements": ["US-Panama TPA", "EU-Central America AA", "Panama-Taiwan FTA"],
        "import_requirements": ["Declaración de Importación", "Factura Comercial", "Conocimiento de Embarque", "Certificado de Origen"],
        "special_notes": "Zona Libre de Colón - mayor zona franca de las Américas. Canal de Panamá."
    },
    "CR": {
        "name": "Costa Rica",
        "name_en": "Costa Rica",
        "region": "América",
        "subregion": "América Central",
        "customs_authority": "Dirección General de Aduanas (DGA)",
        "customs_website": "https://www.hacienda.go.cr/contenido/12437-direccion-general-de-aduanas",
        "tariff_database": "https://www.hacienda.go.cr/ATC/frmConsultaATC.aspx",
        "phytosanitary_authority": "Servicio Fitosanitario del Estado (SFE)",
        "phytosanitary_website": "https://www.sfe.go.cr/",
        "trade_ministry": "PROCOMER",
        "trade_website": "https://www.procomer.com/",
        "eu_member": False,
        "currency": "CRC",
        "vat_rate": 13,
        "reduced_vat": [4, 2, 1],
        "hs_system": "Sistema Arancelario Centroamericano (SAC)",
        "trade_agreements": ["CAFTA-DR", "EU-Central America AA", "Costa Rica-China FTA"],
        "import_requirements": ["Declaración Única Aduanera (DUA)", "Factura Comercial", "Documento de Transporte", "Certificado de Origen"],
        "special_notes": "Sistema TICA para comercio exterior. Régimen de Zonas Francas."
    },
    "GT": {
        "name": "Guatemala",
        "name_en": "Guatemala",
        "region": "América",
        "subregion": "América Central",
        "customs_authority": "Superintendencia de Administración Tributaria (SAT) - Intendencia de Aduanas",
        "customs_website": "https://portal.sat.gob.gt/portal/aduanas/",
        "tariff_database": "https://portal.sat.gob.gt/portal/consulta-arancel/",
        "phytosanitary_authority": "Ministerio de Agricultura, Ganadería y Alimentación (MAGA)",
        "phytosanitary_website": "https://www.maga.gob.gt/",
        "trade_ministry": "Ministerio de Economía",
        "trade_website": "https://www.mineco.gob.gt/",
        "eu_member": False,
        "currency": "GTQ",
        "vat_rate": 12,
        "reduced_vat": [],
        "hs_system": "Sistema Arancelario Centroamericano (SAC)",
        "trade_agreements": ["CAFTA-DR", "EU-Central America AA", "Guatemala-Taiwan FTA"],
        "import_requirements": ["DUCA (Declaración Única Centroamericana)", "Factura Comercial", "Documento de Transporte"],
        "special_notes": "Mayor economía de Centroamérica. Sistema DUCA."
    },
    "DO": {
        "name": "República Dominicana",
        "name_en": "Dominican Republic",
        "region": "América",
        "subregion": "Caribe",
        "customs_authority": "Dirección General de Aduanas (DGA)",
        "customs_website": "https://www.aduanas.gob.do/",
        "tariff_database": "https://www.aduanas.gob.do/arancel/",
        "phytosanitary_authority": "Ministerio de Agricultura",
        "phytosanitary_website": "https://www.agricultura.gob.do/",
        "trade_ministry": "Centro de Exportación e Inversión de la República Dominicana (CEI-RD)",
        "trade_website": "https://www.cei-rd.gob.do/",
        "eu_member": False,
        "currency": "DOP",
        "vat_rate": 18,
        "reduced_vat": [16, 0],
        "hs_system": "Arancel de Aduanas de República Dominicana",
        "trade_agreements": ["CAFTA-DR", "DR-CARICOM", "EU-CARIFORUM EPA"],
        "import_requirements": ["Declaración Única Aduanera", "Factura Comercial", "Conocimiento de Embarque", "Certificado de Origen"],
        "special_notes": "Zonas Francas importantes. Sistema SIGA."
    },
    "JM": {
        "name": "Jamaica",
        "name_en": "Jamaica",
        "region": "América",
        "subregion": "Caribe",
        "customs_authority": "Jamaica Customs Agency (JCA)",
        "customs_website": "https://www.jacustoms.gov.jm/",
        "tariff_database": "https://www.jacustoms.gov.jm/tariff",
        "phytosanitary_authority": "Ministry of Agriculture and Fisheries",
        "phytosanitary_website": "https://www.moa.gov.jm/",
        "trade_ministry": "JAMPRO",
        "trade_website": "https://www.jamaicatradeandinvest.org/",
        "eu_member": False,
        "currency": "JMD",
        "vat_rate": 15,
        "reduced_vat": [0],
        "hs_system": "CARICOM Common External Tariff",
        "trade_agreements": ["CARICOM", "EU-CARIFORUM EPA", "Jamaica-Cuba"],
        "import_requirements": ["Customs Declaration (C78)", "Commercial Invoice", "Bill of Lading", "Certificate of Origin"],
        "special_notes": "Miembro del CARICOM. Sistema ASYCUDA."
    },
    
    # ========================
    # ASIA - ESTE
    # ========================
    "CN": {
        "name": "China",
        "name_en": "China",
        "region": "Asia",
        "subregion": "Asia Oriental",
        "customs_authority": "General Administration of Customs of China (GACC)",
        "customs_website": "http://english.customs.gov.cn/",
        "tariff_database": "http://www.customs.gov.cn/customs/302249/302266/index.html",
        "phytosanitary_authority": "GACC (integrated)",
        "phytosanitary_website": "http://english.customs.gov.cn/",
        "trade_ministry": "Ministry of Commerce (MOFCOM)",
        "trade_website": "http://english.mofcom.gov.cn/",
        "eu_member": False,
        "currency": "CNY",
        "vat_rate": 13,
        "reduced_vat": [9, 6, 0],
        "hs_system": "Chinese Customs Tariff",
        "trade_agreements": ["RCEP", "China-ASEAN FTA", "China-Australia FTA", "China-New Zealand FTA", "China-Switzerland FTA"],
        "import_requirements": [
            "Import Declaration",
            "Commercial Invoice",
            "Bill of Lading/Airway Bill",
            "Packing List",
            "Contract",
            "CCC Certificate (mandatory products)",
            "GACC Registration (food exporters)"
        ],
        "special_notes": "Registro GACC obligatorio para exportadores de alimentos. Certificación CCC para productos regulados."
    },
    "JP": {
        "name": "Japón",
        "name_en": "Japan",
        "region": "Asia",
        "subregion": "Asia Oriental",
        "customs_authority": "Japan Customs (Ministry of Finance)",
        "customs_website": "https://www.customs.go.jp/english/",
        "tariff_database": "https://www.customs.go.jp/english/tariff/",
        "phytosanitary_authority": "Ministry of Agriculture, Forestry and Fisheries (MAFF)",
        "phytosanitary_website": "https://www.maff.go.jp/e/",
        "trade_ministry": "JETRO",
        "trade_website": "https://www.jetro.go.jp/en/",
        "eu_member": False,
        "currency": "JPY",
        "vat_rate": 10,
        "reduced_vat": [8],
        "hs_system": "Japan Customs Tariff",
        "trade_agreements": ["RCEP", "CPTPP", "Japan-EU EPA", "Japan-UK CEPA", "Japan-US Trade Agreement"],
        "import_requirements": [
            "Import Declaration (NACCS)",
            "Commercial Invoice",
            "Bill of Lading",
            "Certificate of Origin",
            "Phytosanitary Certificate (plant products)",
            "JAS Certificate (organic products)"
        ],
        "special_notes": "Sistema NACCS para declaraciones electrónicas. Altos estándares de calidad."
    },
    "KR": {
        "name": "Corea del Sur",
        "name_en": "South Korea",
        "region": "Asia",
        "subregion": "Asia Oriental",
        "customs_authority": "Korea Customs Service (KCS)",
        "customs_website": "https://www.customs.go.kr/english/",
        "tariff_database": "https://unipass.customs.go.kr/",
        "phytosanitary_authority": "Animal and Plant Quarantine Agency (APQA)",
        "phytosanitary_website": "https://www.qia.go.kr/english/",
        "trade_ministry": "KOTRA",
        "trade_website": "https://www.kotra.or.kr/",
        "eu_member": False,
        "currency": "KRW",
        "vat_rate": 10,
        "reduced_vat": [0],
        "hs_system": "Korea Customs Tariff",
        "trade_agreements": ["RCEP", "Korea-EU FTA", "Korea-US FTA (KORUS)", "Korea-UK FTA", "Korea-China FTA"],
        "import_requirements": [
            "Import Declaration (UNI-PASS)",
            "Commercial Invoice",
            "Bill of Lading",
            "Certificate of Origin",
            "KC Mark (safety certification)"
        ],
        "special_notes": "Sistema UNI-PASS para comercio electrónico. Certificación KC obligatoria."
    },
    "TW": {
        "name": "Taiwán",
        "name_en": "Taiwan",
        "region": "Asia",
        "subregion": "Asia Oriental",
        "customs_authority": "Customs Administration, Ministry of Finance",
        "customs_website": "https://web.customs.gov.tw/",
        "tariff_database": "https://portal.sw.nat.gov.tw/",
        "phytosanitary_authority": "Bureau of Animal and Plant Health Inspection and Quarantine (BAPHIQ)",
        "phytosanitary_website": "https://www.baphiq.gov.tw/",
        "trade_ministry": "Bureau of Foreign Trade",
        "trade_website": "https://www.trade.gov.tw/",
        "eu_member": False,
        "currency": "TWD",
        "vat_rate": 5,
        "reduced_vat": [],
        "hs_system": "Taiwan Customs Import Tariff",
        "trade_agreements": ["Taiwan-Panama FTA", "Taiwan-Guatemala FTA", "ECFA (with China)"],
        "import_requirements": ["Import Declaration", "Commercial Invoice", "Bill of Lading", "Certificate of Origin"],
        "special_notes": "Sistema CPT Single Window. IVA bajo (5%)."
    },
    "HK": {
        "name": "Hong Kong",
        "name_en": "Hong Kong",
        "region": "Asia",
        "subregion": "Asia Oriental",
        "customs_authority": "Customs and Excise Department",
        "customs_website": "https://www.customs.gov.hk/",
        "tariff_database": "https://www.tid.gov.hk/english/import_export/",
        "trade_ministry": "Trade and Industry Department",
        "trade_website": "https://www.tid.gov.hk/",
        "eu_member": False,
        "currency": "HKD",
        "vat_rate": 0,
        "tax_note": "Puerto libre - sin aranceles ni IVA",
        "hs_system": "Hong Kong Harmonized System",
        "trade_agreements": ["CEPA (with China)", "Hong Kong-ASEAN FTA", "Hong Kong-Chile FTA"],
        "import_requirements": ["Import/Export Declaration", "Commercial Invoice", "Bill of Lading"],
        "special_notes": "Puerto libre. Sin aranceles excepto alcohol, tabaco, hidrocarburos y metanol."
    },
    "SG": {
        "name": "Singapur",
        "name_en": "Singapore",
        "region": "Asia",
        "subregion": "Sudeste Asiático",
        "customs_authority": "Singapore Customs",
        "customs_website": "https://www.customs.gov.sg/",
        "tariff_database": "https://www.customs.gov.sg/businesses/harmonised-system-classification",
        "phytosanitary_authority": "Singapore Food Agency (SFA)",
        "phytosanitary_website": "https://www.sfa.gov.sg/",
        "trade_ministry": "Enterprise Singapore",
        "trade_website": "https://www.enterprisesg.gov.sg/",
        "eu_member": False,
        "currency": "SGD",
        "vat_rate": 9,
        "reduced_vat": [],
        "hs_system": "Singapore Trade Classification, Customs and Excise Duties",
        "trade_agreements": ["RCEP", "CPTPP", "EU-Singapore FTA", "US-Singapore FTA", "ASEAN"],
        "import_requirements": ["TradeNet Declaration", "Commercial Invoice", "Bill of Lading", "Certificate of Origin"],
        "special_notes": "Puerto libre con aranceles solo en alcohol, tabaco, vehículos y petróleo. GST 9%."
    },
    
    # ========================
    # ASIA - SUDESTE
    # ========================
    "TH": {
        "name": "Tailandia",
        "name_en": "Thailand",
        "region": "Asia",
        "subregion": "Sudeste Asiático",
        "customs_authority": "Thai Customs Department",
        "customs_website": "https://www.customs.go.th/",
        "tariff_database": "https://www.customs.go.th/tariff_rate_search.php",
        "phytosanitary_authority": "Department of Agriculture",
        "phytosanitary_website": "https://www.doa.go.th/",
        "trade_ministry": "Department of International Trade Promotion (DITP)",
        "trade_website": "https://www.ditp.go.th/",
        "eu_member": False,
        "currency": "THB",
        "vat_rate": 7,
        "reduced_vat": [],
        "hs_system": "Thailand Customs Tariff",
        "trade_agreements": ["RCEP", "ASEAN", "Thailand-Australia FTA", "Thailand-New Zealand CEPA", "Thailand-Japan EPA"],
        "import_requirements": ["Import Declaration", "Commercial Invoice", "Bill of Lading", "Certificate of Origin", "FDA Registration (food/cosmetics)"],
        "special_notes": "Sistema NSW (National Single Window). IVA bajo (7%)."
    },
    "VN": {
        "name": "Vietnam",
        "name_en": "Vietnam",
        "region": "Asia",
        "subregion": "Sudeste Asiático",
        "customs_authority": "General Department of Vietnam Customs",
        "customs_website": "https://www.customs.gov.vn/",
        "tariff_database": "https://www.customs.gov.vn/bieuThue.aspx",
        "phytosanitary_authority": "Plant Protection Department",
        "phytosanitary_website": "https://www.ppd.gov.vn/",
        "trade_ministry": "Ministry of Industry and Trade (MOIT)",
        "trade_website": "https://www.moit.gov.vn/",
        "eu_member": False,
        "currency": "VND",
        "vat_rate": 10,
        "reduced_vat": [5, 0],
        "hs_system": "Vietnam Import-Export Tariff",
        "trade_agreements": ["RCEP", "CPTPP", "EU-Vietnam FTA (EVFTA)", "Vietnam-UK FTA", "ASEAN"],
        "import_requirements": ["Customs Declaration", "Commercial Invoice", "Bill of Lading", "Certificate of Origin", "Technical Standards Certificate"],
        "special_notes": "EVFTA elimina 99% de aranceles con UE progresivamente. Sistema VNACCS."
    },
    "ID": {
        "name": "Indonesia",
        "name_en": "Indonesia",
        "region": "Asia",
        "subregion": "Sudeste Asiático",
        "customs_authority": "Direktorat Jenderal Bea dan Cukai (DJBC)",
        "customs_website": "https://www.beacukai.go.id/",
        "tariff_database": "https://www.beacukai.go.id/btki",
        "phytosanitary_authority": "Badan Karantina Pertanian",
        "phytosanitary_website": "https://karantina.pertanian.go.id/",
        "trade_ministry": "Ministry of Trade",
        "trade_website": "https://www.kemendag.go.id/",
        "eu_member": False,
        "currency": "IDR",
        "vat_rate": 11,
        "reduced_vat": [],
        "hs_system": "Indonesia Customs Tariff (BTKI)",
        "trade_agreements": ["RCEP", "ASEAN", "Indonesia-Australia CEPA", "Indonesia-EFTA CEPA", "Indonesia-Korea CEPA"],
        "import_requirements": [
            "Import Declaration (PIB)",
            "Commercial Invoice",
            "Bill of Lading",
            "Certificate of Origin",
            "SNI Certificate (mandatory products)",
            "Halal Certificate (food)"
        ],
        "special_notes": "Sistema INSW. Certificación SNI obligatoria. Halal obligatorio para alimentos."
    },
    "MY": {
        "name": "Malasia",
        "name_en": "Malaysia",
        "region": "Asia",
        "subregion": "Sudeste Asiático",
        "customs_authority": "Royal Malaysian Customs Department (RMCD)",
        "customs_website": "https://www.customs.gov.my/",
        "tariff_database": "https://myhst.customs.gov.my/",
        "phytosanitary_authority": "Department of Agriculture (DOA)",
        "phytosanitary_website": "https://www.doa.gov.my/",
        "trade_ministry": "MATRADE",
        "trade_website": "https://www.matrade.gov.my/",
        "eu_member": False,
        "currency": "MYR",
        "vat_rate": 0,
        "sales_tax": 10,
        "service_tax": 8,
        "hs_system": "Malaysian Customs Tariff",
        "trade_agreements": ["RCEP", "CPTPP", "ASEAN", "Malaysia-Australia FTA", "Malaysia-Turkey FTA"],
        "import_requirements": ["Customs Declaration (K1)", "Commercial Invoice", "Bill of Lading", "Certificate of Origin", "SIRIM Approval (regulated products)"],
        "special_notes": "Sin IVA. Sales Tax 10% + Service Tax 8%. Sistema uCustoms."
    },
    "PH": {
        "name": "Filipinas",
        "name_en": "Philippines",
        "region": "Asia",
        "subregion": "Sudeste Asiático",
        "customs_authority": "Bureau of Customs (BOC)",
        "customs_website": "https://customs.gov.ph/",
        "tariff_database": "https://customs.gov.ph/tariff-commission/",
        "phytosanitary_authority": "Bureau of Plant Industry (BPI)",
        "phytosanitary_website": "https://bpi.da.gov.ph/",
        "trade_ministry": "Department of Trade and Industry (DTI)",
        "trade_website": "https://www.dti.gov.ph/",
        "eu_member": False,
        "currency": "PHP",
        "vat_rate": 12,
        "reduced_vat": [0],
        "hs_system": "ASEAN Harmonized Tariff Nomenclature (AHTN)",
        "trade_agreements": ["RCEP", "ASEAN", "Philippines-Japan EPA", "Philippines-EFTA FTA"],
        "import_requirements": ["Import Entry Declaration", "Commercial Invoice", "Bill of Lading", "Certificate of Origin", "BPI Import Clearance (plants)"],
        "special_notes": "Sistema E2M Customs. Zonas Económicas Especiales (PEZA)."
    },
    
    # ========================
    # ASIA - SUR
    # ========================
    "IN": {
        "name": "India",
        "name_en": "India",
        "region": "Asia",
        "subregion": "Asia del Sur",
        "customs_authority": "Central Board of Indirect Taxes and Customs (CBIC)",
        "customs_website": "https://www.cbic.gov.in/",
        "tariff_database": "https://www.icegate.gov.in/",
        "phytosanitary_authority": "Directorate of Plant Protection, Quarantine & Storage",
        "phytosanitary_website": "https://ppqs.gov.in/",
        "trade_ministry": "Directorate General of Foreign Trade (DGFT)",
        "trade_website": "https://www.dgft.gov.in/",
        "eu_member": False,
        "currency": "INR",
        "vat_rate": 18,
        "gst_note": "GST: 5%, 12%, 18%, 28% según producto",
        "hs_system": "Indian Customs Tariff",
        "trade_agreements": ["India-ASEAN FTA", "India-Japan CEPA", "India-Korea CEPA", "India-UAE CEPA"],
        "import_requirements": [
            "Bill of Entry",
            "Commercial Invoice",
            "Bill of Lading",
            "Import License (restricted items)",
            "BIS Certificate (Bureau of Indian Standards)",
            "Phytosanitary Certificate (plants)"
        ],
        "special_notes": "Sistema ICEGATE. GST con múltiples tasas. Certificación BIS obligatoria para muchos productos."
    },
    
    # ========================
    # MEDIO ORIENTE
    # ========================
    "AE": {
        "name": "Emiratos Árabes Unidos",
        "name_en": "United Arab Emirates",
        "region": "Asia",
        "subregion": "Medio Oriente",
        "customs_authority": "Federal Customs Authority / Dubai Customs",
        "customs_website": "https://www.dubaicustoms.gov.ae/",
        "tariff_database": "https://www.dubaicustoms.gov.ae/en/TradeInformation/",
        "phytosanitary_authority": "Ministry of Climate Change and Environment",
        "phytosanitary_website": "https://www.moccae.gov.ae/",
        "trade_ministry": "Ministry of Economy",
        "trade_website": "https://www.moec.gov.ae/",
        "eu_member": False,
        "currency": "AED",
        "vat_rate": 5,
        "reduced_vat": [0],
        "hs_system": "GCC Common Customs Tariff",
        "trade_agreements": ["GCC Customs Union", "UAE-Israel FTA", "UAE-Indonesia CEPA", "UAE-India CEPA"],
        "import_requirements": ["Import Declaration", "Commercial Invoice", "Certificate of Origin", "Bill of Lading", "Halal Certificate (food)"],
        "special_notes": "Zonas Francas (JAFZA, DAFZA). Arancel general 5%. Certificación Halal obligatoria."
    },
    "SA": {
        "name": "Arabia Saudita",
        "name_en": "Saudi Arabia",
        "region": "Asia",
        "subregion": "Medio Oriente",
        "customs_authority": "Zakat, Tax and Customs Authority (ZATCA)",
        "customs_website": "https://zatca.gov.sa/",
        "tariff_database": "https://zatca.gov.sa/en/eServices/",
        "phytosanitary_authority": "Saudi Food and Drug Authority (SFDA)",
        "phytosanitary_website": "https://www.sfda.gov.sa/",
        "trade_ministry": "Ministry of Commerce",
        "trade_website": "https://mc.gov.sa/",
        "eu_member": False,
        "currency": "SAR",
        "vat_rate": 15,
        "reduced_vat": [0],
        "hs_system": "GCC Common Customs Tariff",
        "trade_agreements": ["GCC Customs Union", "Saudi Arabia-Singapore FTA (negotiating)"],
        "import_requirements": [
            "Import Declaration",
            "Commercial Invoice",
            "Certificate of Origin",
            "SASO Certificate of Conformity",
            "Halal Certificate (food)",
            "SFDA Registration (food/pharma)"
        ],
        "special_notes": "Certificación SASO obligatoria. Halal obligatorio. Sistema FASAH."
    },
    "IL": {
        "name": "Israel",
        "name_en": "Israel",
        "region": "Asia",
        "subregion": "Medio Oriente",
        "customs_authority": "Israel Tax Authority - Customs",
        "customs_website": "https://www.gov.il/en/departments/customs",
        "tariff_database": "https://shaarolami-query.customs.mof.gov.il/",
        "phytosanitary_authority": "Plant Protection and Inspection Services (PPIS)",
        "phytosanitary_website": "https://www.moag.gov.il/ppis/",
        "trade_ministry": "Israel Export Institute",
        "trade_website": "https://www.export.gov.il/",
        "eu_member": False,
        "currency": "ILS",
        "vat_rate": 17,
        "reduced_vat": [0],
        "hs_system": "Israeli Customs Tariff",
        "trade_agreements": ["EU-Israel Association Agreement", "US-Israel FTA", "Israel-UK FTA", "EFTA-Israel FTA"],
        "import_requirements": ["Import Declaration", "Commercial Invoice", "Bill of Lading", "Certificate of Origin", "Standards Institute of Israel Approval"],
        "special_notes": "TLC con UE, USA y UK. Sistema Shaar Olami."
    },
    "QA": {
        "name": "Catar",
        "name_en": "Qatar",
        "region": "Asia",
        "subregion": "Medio Oriente",
        "customs_authority": "General Authority of Customs",
        "customs_website": "https://www.customs.gov.qa/",
        "tariff_database": "https://www.customs.gov.qa/en/services/tariff",
        "trade_ministry": "Ministry of Commerce and Industry",
        "trade_website": "https://www.moci.gov.qa/",
        "eu_member": False,
        "currency": "QAR",
        "vat_rate": 0,
        "tax_note": "Sin IVA",
        "hs_system": "GCC Common Customs Tariff",
        "trade_agreements": ["GCC Customs Union"],
        "import_requirements": ["Import Declaration", "Commercial Invoice", "Certificate of Origin", "Bill of Lading"],
        "special_notes": "Sin IVA. Arancel general 5%. Certificación Halal para alimentos."
    },
    
    # ========================
    # ÁFRICA
    # ========================
    "ZA": {
        "name": "Sudáfrica",
        "name_en": "South Africa",
        "region": "África",
        "subregion": "África Austral",
        "customs_authority": "South African Revenue Service (SARS) - Customs and Excise",
        "customs_website": "https://www.sars.gov.za/customs-and-excise/",
        "tariff_database": "https://www.sars.gov.za/legal-counsel/sc-rulings/tariff-classification-rulings/",
        "phytosanitary_authority": "Department of Agriculture, Land Reform and Rural Development",
        "phytosanitary_website": "https://www.dalrrd.gov.za/",
        "trade_ministry": "Department of Trade, Industry and Competition",
        "trade_website": "https://www.thedtic.gov.za/",
        "eu_member": False,
        "currency": "ZAR",
        "vat_rate": 15,
        "reduced_vat": [0],
        "hs_system": "South African Customs Tariff",
        "trade_agreements": ["SACU", "SADC", "EU-SADC EPA", "AfCFTA"],
        "import_requirements": ["Bill of Entry (DA500)", "Commercial Invoice", "Bill of Lading", "Certificate of Origin", "Import Permit (restricted goods)"],
        "special_notes": "Sistema RLA. SACU (Unión Aduanera del África Austral). EORI obligatorio."
    },
    "NG": {
        "name": "Nigeria",
        "name_en": "Nigeria",
        "region": "África",
        "subregion": "África Occidental",
        "customs_authority": "Nigeria Customs Service (NCS)",
        "customs_website": "https://customs.gov.ng/",
        "tariff_database": "https://customs.gov.ng/index.php/tariff",
        "phytosanitary_authority": "Nigeria Agricultural Quarantine Service (NAQS)",
        "phytosanitary_website": "https://naqs.gov.ng/",
        "trade_ministry": "Nigerian Export Promotion Council (NEPC)",
        "trade_website": "https://nepc.gov.ng/",
        "eu_member": False,
        "currency": "NGN",
        "vat_rate": 7.5,
        "reduced_vat": [0],
        "hs_system": "ECOWAS Common External Tariff",
        "trade_agreements": ["ECOWAS", "AfCFTA"],
        "import_requirements": ["Single Goods Declaration (SGD)", "Commercial Invoice", "Bill of Lading", "Form M (import approval)", "SON Certificate (Standards)"],
        "special_notes": "Mayor economía de África. Sistema B'Odogwu. Certificación SON obligatoria."
    },
    "EG": {
        "name": "Egipto",
        "name_en": "Egypt",
        "region": "África",
        "subregion": "Norte de África",
        "customs_authority": "Egyptian Customs Authority",
        "customs_website": "https://www.customs.gov.eg/",
        "tariff_database": "https://www.customs.gov.eg/en/Traders/Tariff",
        "phytosanitary_authority": "Central Administration of Plant Quarantine (CAPQ)",
        "phytosanitary_website": "https://capq.gov.eg/",
        "trade_ministry": "General Organization for Export and Import Control (GOEIC)",
        "trade_website": "https://www.goeic.gov.eg/",
        "eu_member": False,
        "currency": "EGP",
        "vat_rate": 14,
        "reduced_vat": [0],
        "hs_system": "Egyptian Customs Tariff",
        "trade_agreements": ["EU-Egypt Association Agreement", "COMESA", "GAFTA", "AfCFTA", "Egypt-Turkey FTA"],
        "import_requirements": ["Import Declaration", "Commercial Invoice", "Bill of Lading", "Certificate of Origin", "GOEIC Inspection Certificate"],
        "special_notes": "Canal de Suez. Sistema NAFEZA. TLCs con UE y múltiples países árabes."
    },
    "MA": {
        "name": "Marruecos",
        "name_en": "Morocco",
        "region": "África",
        "subregion": "Norte de África",
        "customs_authority": "Administration des Douanes et Impôts Indirects (ADII)",
        "customs_website": "https://www.douane.gov.ma/",
        "tariff_database": "https://www.douane.gov.ma/web/guest/tarif-douanier",
        "phytosanitary_authority": "Office National de Sécurité Sanitaire des Produits Alimentaires (ONSSA)",
        "phytosanitary_website": "http://www.onssa.gov.ma/",
        "trade_ministry": "Maroc Export",
        "trade_website": "https://www.marocexport.gov.ma/",
        "eu_member": False,
        "currency": "MAD",
        "vat_rate": 20,
        "reduced_vat": [14, 10, 7, 0],
        "hs_system": "Moroccan Customs Tariff",
        "trade_agreements": ["EU-Morocco Association Agreement", "US-Morocco FTA", "Morocco-Turkey FTA", "AfCFTA", "Agadir Agreement"],
        "import_requirements": ["Déclaration en Douane", "Facture Commerciale", "Connaissement", "Certificat d'Origine", "Certificat Sanitaire (aliments)"],
        "special_notes": "TLC con UE y USA. Tánger-Med - mayor puerto de África."
    },
    "KE": {
        "name": "Kenia",
        "name_en": "Kenya",
        "region": "África",
        "subregion": "África Oriental",
        "customs_authority": "Kenya Revenue Authority (KRA) - Customs",
        "customs_website": "https://www.kra.go.ke/",
        "tariff_database": "https://www.kra.go.ke/business/customs/customs-services",
        "phytosanitary_authority": "Kenya Plant Health Inspectorate Service (KEPHIS)",
        "phytosanitary_website": "https://www.kephis.org/",
        "trade_ministry": "Kenya Export Promotion and Branding Agency (KEPROBA)",
        "trade_website": "https://www.keproba.go.ke/",
        "eu_member": False,
        "currency": "KES",
        "vat_rate": 16,
        "reduced_vat": [8, 0],
        "hs_system": "EAC Common External Tariff",
        "trade_agreements": ["EAC", "COMESA", "AfCFTA", "EU-EAC EPA"],
        "import_requirements": ["Import Declaration Form (IDF)", "Commercial Invoice", "Bill of Lading", "Certificate of Origin", "KEBS Certificate (Standards)"],
        "special_notes": "Hub de África Oriental. Puerto de Mombasa. Sistema iCMS."
    },
    "GH": {
        "name": "Ghana",
        "name_en": "Ghana",
        "region": "África",
        "subregion": "África Occidental",
        "customs_authority": "Ghana Revenue Authority (GRA) - Customs Division",
        "customs_website": "https://gra.gov.gh/",
        "tariff_database": "https://gra.gov.gh/customs/",
        "phytosanitary_authority": "Plant Protection and Regulatory Services Directorate (PPRSD)",
        "phytosanitary_website": "https://mofa.gov.gh/site/directorates/pprsd",
        "trade_ministry": "Ghana Export Promotion Authority (GEPA)",
        "trade_website": "https://www.gepaghana.org/",
        "eu_member": False,
        "currency": "GHS",
        "vat_rate": 15,
        "reduced_vat": [],
        "hs_system": "ECOWAS Common External Tariff",
        "trade_agreements": ["ECOWAS", "AfCFTA", "EU-Ghana EPA"],
        "import_requirements": ["Bill of Entry", "Commercial Invoice", "Bill of Lading", "Certificate of Origin", "Import Declaration Form (IDF)"],
        "special_notes": "Sede del AfCFTA. Puerto de Tema. Sistema GCNet/UNIPASS."
    },
    
    # ========================
    # OCEANÍA
    # ========================
    "AU": {
        "name": "Australia",
        "name_en": "Australia",
        "region": "Oceanía",
        "subregion": "Australia y Nueva Zelanda",
        "customs_authority": "Australian Border Force (ABF)",
        "customs_website": "https://www.abf.gov.au/",
        "tariff_database": "https://www.abf.gov.au/importing-exporting-and-manufacturing/tariff-classification",
        "phytosanitary_authority": "Department of Agriculture, Fisheries and Forestry (DAFF)",
        "phytosanitary_website": "https://www.agriculture.gov.au/biosecurity",
        "trade_ministry": "Austrade",
        "trade_website": "https://www.austrade.gov.au/",
        "eu_member": False,
        "currency": "AUD",
        "vat_rate": 10,
        "reduced_vat": [0],
        "hs_system": "Australian Customs Tariff",
        "trade_agreements": ["RCEP", "CPTPP", "Australia-UK FTA", "Australia-US FTA", "ANZCERTA", "AANZFTA"],
        "import_requirements": [
            "Import Declaration (N10)",
            "Commercial Invoice",
            "Bill of Lading",
            "Certificate of Origin",
            "Biosecurity Import Permit (regulated goods)",
            "Therapeutic Goods Administration Approval (medicines)"
        ],
        "special_notes": "Estrictos controles de bioseguridad. Sistema ICS (Integrated Cargo System)."
    },
    "NZ": {
        "name": "Nueva Zelanda",
        "name_en": "New Zealand",
        "region": "Oceanía",
        "subregion": "Australia y Nueva Zelanda",
        "customs_authority": "New Zealand Customs Service",
        "customs_website": "https://www.customs.govt.nz/",
        "tariff_database": "https://www.customs.govt.nz/business/tariff/",
        "phytosanitary_authority": "Ministry for Primary Industries (MPI)",
        "phytosanitary_website": "https://www.mpi.govt.nz/",
        "trade_ministry": "New Zealand Trade and Enterprise (NZTE)",
        "trade_website": "https://www.nzte.govt.nz/",
        "eu_member": False,
        "currency": "NZD",
        "vat_rate": 15,
        "reduced_vat": [0],
        "hs_system": "New Zealand Tariff",
        "trade_agreements": ["RCEP", "CPTPP", "NZ-UK FTA", "ANZCERTA", "NZ-China FTA", "AANZFTA"],
        "import_requirements": ["Import Declaration", "Commercial Invoice", "Bill of Lading", "Certificate of Origin", "MPI Import Health Standard"],
        "special_notes": "Estrictos controles de bioseguridad. Sistema JBMS. TLCs extensivos."
    }
}

# Información de tratados comerciales principales
TRADE_AGREEMENTS_INFO = {
    "EU Single Market": {
        "name": "Mercado Único Europeo",
        "members": ["AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE"],
        "type": "Customs Union + Single Market",
        "tariff_elimination": "100%",
        "website": "https://ec.europa.eu/growth/single-market_en"
    },
    "USMCA": {
        "name": "United States-Mexico-Canada Agreement (T-MEC)",
        "name_es": "Tratado entre México, Estados Unidos y Canadá",
        "members": ["US", "MX", "CA"],
        "type": "Free Trade Agreement",
        "tariff_elimination": "99%+",
        "website": "https://ustr.gov/trade-agreements/free-trade-agreements/united-states-mexico-canada-agreement"
    },
    "RCEP": {
        "name": "Regional Comprehensive Economic Partnership",
        "name_es": "Asociación Económica Integral Regional",
        "members": ["AU", "BN", "KH", "CN", "ID", "JP", "KR", "LA", "MY", "MM", "NZ", "PH", "SG", "TH", "VN"],
        "type": "Free Trade Agreement",
        "tariff_elimination": "90%+",
        "website": "https://rcepsec.org/"
    },
    "CPTPP": {
        "name": "Comprehensive and Progressive Agreement for Trans-Pacific Partnership",
        "name_es": "Tratado Integral y Progresista de Asociación Transpacífico",
        "members": ["AU", "BN", "CA", "CL", "JP", "MY", "MX", "NZ", "PE", "SG", "VN", "GB"],
        "type": "Free Trade Agreement",
        "tariff_elimination": "95%+",
        "website": "https://www.mfat.govt.nz/en/trade/free-trade-agreements/free-trade-agreements-in-force/cptpp/"
    },
    "AfCFTA": {
        "name": "African Continental Free Trade Area",
        "name_es": "Área de Libre Comercio Continental Africana",
        "members": ["ZA", "NG", "EG", "MA", "KE", "GH"],
        "all_members": "54 países de la Unión Africana",
        "type": "Free Trade Agreement",
        "tariff_elimination": "90% (progressive)",
        "website": "https://au-afcfta.org/"
    },
    "MERCOSUR": {
        "name": "Mercado Común del Sur",
        "members": ["AR", "BR", "PY", "UY"],
        "associates": ["BO", "CL", "CO", "EC", "GY", "PE", "SR"],
        "type": "Customs Union",
        "tariff_elimination": "100% intra-bloque",
        "website": "https://www.mercosur.int/"
    },
    "Pacific Alliance": {
        "name": "Alianza del Pacífico",
        "members": ["CL", "CO", "MX", "PE"],
        "observers": ["CR", "PA", "EC"],
        "type": "Free Trade Agreement",
        "tariff_elimination": "92%",
        "website": "https://alianzapacifico.net/"
    },
    "CAN": {
        "name": "Comunidad Andina de Naciones",
        "name_en": "Andean Community",
        "members": ["CO", "PE", "EC", "BO"],
        "former_members": ["VE"],
        "type": "Free Trade Area",
        "tariff_elimination": "100% intra-bloque",
        "website": "https://www.comunidadandina.org/",
        "notes": "Venezuela se retiró en 2006. Libre comercio entre miembros activos."
    },
    "ASEAN": {
        "name": "Association of Southeast Asian Nations",
        "name_es": "Asociación de Naciones del Sudeste Asiático",
        "members": ["BN", "KH", "ID", "LA", "MY", "MM", "PH", "SG", "TH", "VN"],
        "type": "Free Trade Area",
        "tariff_elimination": "96% (AFTA)",
        "website": "https://asean.org/"
    },
    "GCC": {
        "name": "Gulf Cooperation Council Customs Union",
        "name_es": "Consejo de Cooperación del Golfo",
        "members": ["AE", "BH", "KW", "OM", "QA", "SA"],
        "type": "Customs Union",
        "common_tariff": "5%",
        "website": "https://www.gcc-sg.org/"
    },
    "EFTA": {
        "name": "European Free Trade Association",
        "name_es": "Asociación Europea de Libre Comercio",
        "members": ["CH", "IS", "LI", "NO"],
        "type": "Free Trade Association",
        "website": "https://www.efta.int/"
    },
    "EU-Colombia-Peru-Ecuador": {
        "name": "EU-Colombia/Peru/Ecuador Trade Agreement",
        "name_es": "Acuerdo Comercial UE-Colombia/Perú/Ecuador",
        "members": ["CO", "PE", "EC"],
        "with": ["EU countries"],
        "type": "Free Trade Agreement",
        "tariff_elimination": "99%+ industrial goods",
        "website": "https://trade.ec.europa.eu/access-to-markets/es/content/acuerdo-comercial-ue-colombia-peru-ecuador"
    },
    "US-Colombia TPA": {
        "name": "US-Colombia Trade Promotion Agreement",
        "name_es": "TLC Estados Unidos - Colombia",
        "members": ["US", "CO"],
        "type": "Free Trade Agreement",
        "since": 2012,
        "website": "https://ustr.gov/trade-agreements/free-trade-agreements/colombia-tpa"
    },
    "EU-Mexico": {
        "name": "EU-Mexico Global Agreement",
        "members": ["MX"],
        "with": ["EU countries"],
        "type": "Free Trade Agreement",
        "website": "https://policy.trade.ec.europa.eu/eu-trade-relationships-country-and-region/countries-and-regions/mexico_en"
    },
    "EU-Japan EPA": {
        "name": "EU-Japan Economic Partnership Agreement",
        "members": ["JP"],
        "with": ["EU countries"],
        "type": "Economic Partnership Agreement",
        "since": 2019,
        "tariff_elimination": "97%",
        "website": "https://trade.ec.europa.eu/access-to-markets/en/content/eu-japan-economic-partnership-agreement"
    },
    "EU-Canada CETA": {
        "name": "Comprehensive Economic and Trade Agreement",
        "members": ["CA"],
        "with": ["EU countries"],
        "type": "Free Trade Agreement",
        "since": 2017,
        "website": "https://policy.trade.ec.europa.eu/eu-trade-relationships-country-and-region/countries-and-regions/canada_en"
    },
    "EU-UK TCA": {
        "name": "EU-UK Trade and Cooperation Agreement",
        "members": ["GB"],
        "with": ["EU countries"],
        "type": "Free Trade Agreement",
        "since": 2021,
        "tariff_elimination": "Zero tariffs, zero quotas (with rules of origin)",
        "website": "https://ec.europa.eu/info/strategy/relations-non-eu-countries/relations-united-kingdom/eu-uk-trade-and-cooperation-agreement_en"
    },
    "China-ASEAN FTA": {
        "name": "China-ASEAN Free Trade Agreement (CAFTA)",
        "members": ["CN"],
        "with": ["BN", "KH", "ID", "LA", "MY", "MM", "PH", "SG", "TH", "VN"],
        "type": "Free Trade Agreement",
        "since": 2010,
        "website": "http://fta.mofcom.gov.cn/"
    },
    "India-ASEAN FTA": {
        "name": "ASEAN-India Free Trade Agreement (AIFTA)",
        "members": ["IN"],
        "with": ["BN", "KH", "ID", "LA", "MY", "MM", "PH", "SG", "TH", "VN"],
        "type": "Free Trade Agreement",
        "since": 2010
    },
    "Australia-China FTA": {
        "name": "China-Australia Free Trade Agreement (ChAFTA)",
        "members": ["AU", "CN"],
        "type": "Free Trade Agreement",
        "since": 2015
    },
    "UK-Australia FTA": {
        "name": "UK-Australia Free Trade Agreement",
        "members": ["GB", "AU"],
        "type": "Free Trade Agreement",
        "since": 2023
    },
    "SACU": {
        "name": "Southern African Customs Union",
        "members": ["ZA", "BW", "LS", "NA", "SZ"],
        "type": "Customs Union",
        "website": "https://www.sacu.int/"
    },
    "SADC": {
        "name": "Southern African Development Community",
        "members": ["ZA", "BW", "LS", "NA", "SZ", "MZ", "ZW", "ZM", "MW", "TZ", "AO", "CD", "MG", "MU", "SC", "KM"],
        "type": "Free Trade Area",
        "website": "https://www.sadc.int/"
    },
    "ECOWAS": {
        "name": "Economic Community of West African States",
        "name_es": "Comunidad Económica de Estados de África Occidental",
        "members": ["NG", "GH", "SN", "CI", "ML", "BF", "NE", "BJ", "TG", "GW", "LR", "SL", "GM", "CV"],
        "type": "Economic Community",
        "website": "https://www.ecowas.int/"
    },
    "EAC": {
        "name": "East African Community",
        "members": ["KE", "UG", "TZ", "RW", "BI", "SS", "CD"],
        "type": "Customs Union",
        "website": "https://www.eac.int/"
    },
    "COMESA": {
        "name": "Common Market for Eastern and Southern Africa",
        "members": ["KE", "EG", "ET", "UG", "ZM", "ZW", "RW", "BI", "ER", "DJ", "SD", "LY", "TN", "CD", "MG", "MU", "SC", "KM", "MW", "SO", "SD", "EG"],
        "type": "Free Trade Area",
        "website": "https://www.comesa.int/"
    },
    "GAFTA": {
        "name": "Greater Arab Free Trade Area",
        "name_es": "Gran Zona Árabe de Libre Comercio",
        "members": ["AE", "SA", "QA", "KW", "BH", "OM", "EG", "JO", "LB", "SY", "IQ", "LY", "TN", "MA", "SD", "SO", "PA", "YE"],
        "type": "Free Trade Area"
    }
}

# Recursos globales de comercio internacional
GLOBAL_RESOURCES = {
    "WTO": {
        "name": "World Trade Organization",
        "name_es": "Organización Mundial del Comercio",
        "website": "https://www.wto.org/",
        "tariff_database": "https://ttd.wto.org/",
        "rta_database": "https://rtais.wto.org/",
        "market_access": "https://stats.wto.org/dashboard/marketaccess_en.html",
        "tariff_profiles": "https://www.wto.org/english/res_e/statis_e/statis_e.htm"
    },
    "WCO": {
        "name": "World Customs Organization",
        "name_es": "Organización Mundial de Aduanas",
        "website": "http://www.wcoomd.org/",
        "hs_nomenclature": "http://www.wcoomd.org/en/topics/nomenclature.aspx"
    },
    "IPPC": {
        "name": "International Plant Protection Convention",
        "name_es": "Convención Internacional de Protección Fitosanitaria",
        "website": "https://www.ippc.int/",
        "phytosanitary_portal": "https://www.ippc.int/en/countries/all/"
    },
    "CODEX": {
        "name": "Codex Alimentarius",
        "name_es": "Codex Alimentarius (Normas Alimentarias)",
        "website": "https://www.fao.org/fao-who-codexalimentarius/",
        "standards": "https://www.fao.org/fao-who-codexalimentarius/codex-texts/list-standards/"
    },
    "ITC": {
        "name": "International Trade Centre",
        "name_es": "Centro de Comercio Internacional",
        "website": "https://www.intracen.org/",
        "market_access": "https://www.macmap.org/",
        "trade_map": "https://www.trademap.org/"
    },
    "UNCTAD": {
        "name": "UN Conference on Trade and Development",
        "name_es": "Conferencia de las Naciones Unidas sobre Comercio y Desarrollo",
        "website": "https://unctad.org/",
        "trains_database": "https://trainsonline.unctad.org/",
        "world_tariff_profiles": "https://unctad.org/publication/world-tariff-profiles-2025"
    },
    "FAO": {
        "name": "Food and Agriculture Organization",
        "name_es": "Organización de las Naciones Unidas para la Alimentación y la Agricultura",
        "website": "https://www.fao.org/",
        "trade_portal": "https://www.fao.org/markets-and-trade/"
    },
    "OIE": {
        "name": "World Organisation for Animal Health (WOAH)",
        "name_es": "Organización Mundial de Sanidad Animal",
        "website": "https://www.woah.org/",
        "standards": "https://www.woah.org/en/what-we-do/standards/"
    }
}

# Aranceles típicos por producto (referencias generales)
TYPICAL_TARIFFS = {
    "cacao": {
        "hs_chapter": "18",
        "hs_heading": "1801",
        "description": "Cacao en grano, entero o partido, crudo o tostado",
        "typical_mfn_rates": {
            "EU": "0%",
            "US": "0%",
            "CO": "5-15%",
            "MX": "10-20%",
            "CN": "8%",
            "JP": "0%"
        }
    },
    "coffee": {
        "hs_chapter": "09",
        "hs_heading": "0901",
        "description": "Café, incluso tostado o descafeinado",
        "typical_mfn_rates": {
            "EU": "0-7.5%",
            "US": "0%",
            "CO": "5%",
            "JP": "0%"
        }
    },
    "textiles": {
        "hs_chapters": ["50-63"],
        "description": "Textiles y confecciones",
        "typical_mfn_rates": {
            "EU": "8-12%",
            "US": "10-32%",
            "CN": "10-25%"
        }
    }
}
